# Generated by Django 4.2.5 on 2023-12-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_brand_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, upload_to='brand_images', verbose_name='Изображение'),
        ),
    ]
